# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ToDoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'ISEmojiView'

  # Pods for ToDoApp

end
